{
"cells": [
{
"cell_type": "code",
"execution_count": 1,
"metadata": {
"collapsed": true
},
"outputs": [],
"source": [
"# Import SQLAlchemy and other dependencies 
",
"# Python SQL toolkit and Object Relational Mapper
",
"import sqlalchemy
",
"from sqlalchemy.ext.automap import automap_base
",
"from sqlalchemy.orm import Session
",
"from sqlalchemy import create_engine, inspect, func
",
"import pandas as pd
",
"from sqlalchemy import Column, Integer, String, Float, Text, ForeignKey
",
"import numpy as np
",
"from sqlalchemy import MetaData
",
"from sqlalchemy import Table"
]
},
{
"cell_type": "code",
"execution_count": 2,
"metadata": {
"collapsed": true
},
"outputs": [],
"source": [
"# Create engine using the `sqlite` database file created in database_engineering steps
",
"
",
"engine = create_engine("sqlite:///belly_button_biodiversity.sqlite")"
]
},
{
"cell_type": "code",
"execution_count": 3,
"metadata": {},
"outputs": [],
"source": [
"# Declare a Base using `automap_base()`
",
"
",
"Base = automap_base()"
]
},
{
"cell_type": "code",
"execution_count": 4,
"metadata": {
"collapsed": true
},
"outputs": [],
"source": [
"# Use the Base class to reflect the database tables
",
"Base.prepare(engine, reflect=True)"
]
},
{
"cell_type": "code",
"execution_count": 5,
"metadata": {},
"outputs": [
{
"data": {
"text/plain": [
"['otu', 'samples', 'samples_metadata']"
]
},
"execution_count": 5,
"metadata": {},
"output_type": "execute_result"
}
],
"source": [
"# Create the inspector and connect it to the engine
",
"inspector = inspect(engine)
",
"
",
"# Collect the names of tables within the database
",
"inspector.get_table_names()"
]
},
{
"cell_type": "code",
"execution_count": 6,
"metadata": {},
"outputs": [
{
"data": {
"text/plain": [
"[{'autoincrement': 'auto',
",
"  'default': None,
",
"  'name': 'otu_id',
",
"  'nullable': False,
",
"  'primary_key': 1,
",
"  'type': INTEGER()},
",
" {'autoincrement': 'auto',
",
"  'default': None,
",
"  'name': 'lowest_taxonomic_unit_found',
",
"  'nullable': True,
",
"  'primary_key': 0,
",
"  'type': TEXT()}]"
]
},
"execution_count": 6,
"metadata": {},
"output_type": "execute_result"
}
],
"source": [
"inspector.get_columns('otu')"
]
},
{
"cell_type": "code",
"execution_count": 7,
"metadata": {},
"outputs": [
{
"data": {
"text/plain": [
"[{'autoincrement': 'auto',
",
"  'default': None,
",
"  'name': 'otu_id',
",
"  'nullable': False,
",
"  'primary_key': 1,
",
"  'type': INTEGER()},
",
" {'autoincrement': 'auto',
",
"  'default': None,
",
"  'name': 'BB_940',
",
"  'nullable': True,
",
"  'primary_key': 0,
",
"  'type': INTEGER()},
",
" {'autoincrement': 'auto',
",
"  'default': None,
",
"  'name': 'BB_941',
",
"  'nullable': True,
",
"  'primary_key': 0,
",
"  'type': INTEGER()},
",
" {'autoincrement': 'auto',
",
"  'default': None,
",
"  'name': 'BB_943',
",
"  'nullable': True,
",
"  'primary_key': 0,
",
"  'type': INTEGER()},
",
" {'autoincrement': 'auto',
",
"  'default': None,
",
"  'name': 'BB_944',
",
"  'nullable': True,
",
"  'primary_key': 0,
",
"  'type': INTEGER()},
",
" {'autoincrement': 'auto',
",
"  'default': None,
",
"  'name': 'BB_945',
",
"  'nullable': True,
",
"  'primary_key': 0,
",
"  'type': INTEGER()},
",
" {'autoincrement': 'auto',
",
"  'default': None,
",
"  'name': 'BB_946',
",
"  'nullable': True,
",
"  'primary_key': 0,
",
"  'type': INTEGER()},
",
" {'autoincrement': 'auto',
",
"  'default': None,
",
"  'name': 'BB_947',
",
"  'nullable': True,
",
"  'primary_key': 0,
",
"  'type': INTEGER()},
",
" {'autoincrement': 'auto',
",
"  'default': None,
",
"  'name': 'BB_948',
",
"  'nullable': True,
",
"  'primary_key': 0,
",
"  'type': INTEGER()},
",
" {'autoincrement': 'auto',
",
"  'default': None,
",
"  'name': 'BB_949',
",
"  'nullable': True,
",
"  'primary_key': 0,
",
"  'type': INTEGER()},
",
" {'autoincrement': 'auto',
",
"  'default': None,
",
"  'name': 'BB_950',
",
"  'nullable': True,
",
"  'primary_key': 0,
",
"  'type': INTEGER()},
",
" {'autoincrement': 'auto',
",
"  'default': None,
",
"  'name': 'BB_952',
",
"  'nullable': True,
",
"  'primary_key': 0,
",
"  'type': INTEGER()},
",
" {'autoincrement': 'auto',
",
"  'default': None,
",
"  'name': 'BB_953',
",
"  'nullable': True,
",
"  'primary_key': 0,
",
"  'type': INTEGER()},
",
" {'autoincrement': 'auto',
",
"  'default': None,
",
"  'name': 'BB_954',
",
"  'nullable': True,
",
"  'primary_key': 0,
",
"  'type': INTEGER()},
",
" {'autoincrement': 'auto',
",
"  'default': None,
",
"  'name': 'BB_955',
",
"  'nullable': True,
",
"  'primary_key': 0,
",
"  'type': INTEGER()},
",
" {'autoincrement': 'auto',
",
"  'default': None,
",
"  'name': 'BB_956',
",
"  'nullable': True,
",
"  'primary_key': 0,
",
"  'type': INTEGER()},
",
" {'autoincrement': 'auto',
",
"  'default': None,
",
"  'name': 'BB_958',
",
"  'nullable': True,
",
"  'primary_key': 0,
",
"  'type': INTEGER()},
",
" {'autoincrement': 'auto',
",
"  'default': None,
",
"  'name': 'BB_959',
",
"  'nullable': True,
",
"  'primary_key': 0,
",
"  'type': INTEGER()},
",
" {'autoincrement': 'auto',
",
"  'default': None,
",
"  'name': 'BB_960',
",
"  'nullable': True,
",
"  'primary_key': 0,
",
"  'type': INTEGER()},
",
" {'autoincrement': 'auto',
",
"  'default': None,
",
"  'name': 'BB_961',
",
"  'nullable': True,
",
"  'primary_key': 0,
",
"  'type': INTEGER()},
",
" {'autoincrement': 'auto',
",
"  'default': None,
",
"  'name': 'BB_962',
",
"  'nullable': True,
",
"  'primary_key': 0,
",
"  'type': INTEGER()},
",
" {'autoincrement': 'auto',
",
"  'default': None,
",
"  'name': 'BB_963',
",
"  'nullable': True,
",
"  'primary_key': 0,
",
"  'type': INTEGER()},
",
" {'autoincrement': 'auto',
",
"  'default': None,
",
"  'name': 'BB_964',
",
"  'nullable': True,
",
"  'primary_key': 0,
",
"  'type': INTEGER()},
",
" {'autoincrement': 'auto',
",
"  'default': None,
",
"  'name': 'BB_966',
",
"  'nullable': True,
",
"  'primary_key': 0,
",
"  'type': INTEGER()},
",
" {'autoincrement': 'auto',
",
"  'default': None,
",
"  'name': 'BB_967',
",
"  'nullable': True,
",
"  'primary_key': 0,
",
"  'type': INTEGER()},
",
" {'autoincrement': 'auto',
",
"  'default': None,
",
"  'name': 'BB_968',
",
"  'nullable': True,
",
"  'primary_key': 0,
",
"  'type': INTEGER()},
",
" {'autoincrement': 'auto',
",
"  'default': None,
",
"  'name': 'BB_969',
",
"  'nullable': True,
",
"  'primary_key': 0,
",
"  'type': INTEGER()},
",
" {'autoincrement': 'auto',
",
"  'default': None,
",
"  'name': 'BB_970',
",
"  'nullable': True,
",
"  'primary_key': 0,
",
"  'type': INTEGER()},
",
" {'autoincrement': 'auto',
",
"  'default': None,
",
"  'name': 'BB_971',
",
"  'nullable': True,
",
"  'primary_key': 0,
",
"  'type': INTEGER()},
",
" {'autoincrement': 'auto',
",
"  'default': None,
",
"  'name': 'BB_972',
",
"  'nullable': True,
",
"  'primary_key': 0,
",
"  'type': INTEGER()},
",
" {'autoincrement': 'auto',
",
"  'default': None,
",
"  'name': 'BB_973',
",
"  'nullable': True,
",
"  'primary_key': 0,
",
"  'type': INTEGER()},
",
" {'autoincrement': 'auto',
",
"  'default': None,
",
"  'name': 'BB_974',
",
"  'nullable': True,
",
"  'primary_key': 0,
",
"  'type': INTEGER()},
",
" {'autoincrement': 'auto',
",
"  'default': None,
",
"  'name': 'BB_975',
",
"  'nullable': True,
",
"  'primary_key': 0,
",
"  'type': INTEGER()},
",
" {'autoincrement': 'auto',
",
"  'default': None,
",
"  'name': 'BB_978',
",
"  'nullable': True,
",
"  'primary_key': 0,
",
"  'type': INTEGER()},
",
" {'autoincrement': 'auto',
",
"  'default': None,
",
"  'name': 'BB_1233',
",
"  'nullable': True,
",
"  'primary_key': 0,
",
"  'type': INTEGER()},
",
" {'autoincrement': 'auto',
",
"  'default': None,
",
"  'name': 'BB_1234',
",
"  'nullable': True,
",
"  'primary_key': 0,
",
"  'type': INTEGER()},
",
" {'autoincrement': 'auto',
",
"  'default': None,
",
"  'name': 'BB_1235',
",
"  'nullable': True,
",
"  'primary_key': 0,
",
"  'type': INTEGER()},
",
" {'autoincrement': 'auto',
",
"  'default': None,
",
"  'name': 'BB_1236',
",
"  'nullable': True,
",
"  'primary_key': 0,
",
"  'type': INTEGER()},
",
" {'autoincrement': 'auto',
",
"  'default': None,
",
"  'name': 'BB_1237',
",
"  'nullable': True,
",
"  'primary_key': 0,
",
"  'type': INTEGER()},
",
" {'autoincrement': 'auto',
",
"  'default': None,
",
"  'name': 'BB_1238',
",
"  'nullable': True,
",
"  'primary_key': 0,
",
"  'type': INTEGER()},
",
" {'autoincrement': 'auto',
",
"  'default': None,
",
"  'name': 'BB_1242',
",
"  'nullable': True,
",
"  'primary_key': 0,
",
"  'type': INTEGER()},
",
" {'autoincrement': 'auto',
",
"  'default': None,
",
"  'name': 'BB_1243',
",
"  'nullable': True,
",
"  'primary_key': 0,
",
"  'type': INTEGER()},
",
" {'autoincrement': 'auto',
",
"  'default': None,
",
"  'name': 'BB_1246',
",
"  'nullable': True,
",
"  'primary_key': 0,
",
"  'type': INTEGER()},
",
" {'autoincrement': 'auto',
",
"  'default': None,
",
"  'name': 'BB_1253',
",
"  'nullable': True,
",
"  'primary_key': 0,
",
"  'type': INTEGER()},
",
" {'autoincrement': 'auto',
",
"  'default': None,
",
"  'name': 'BB_1254',
",
"  'nullable': True,
",
"  'primary_key': 0,
",
"  'type': INTEGER()},
",
" {'autoincrement': 'auto',
",
"  'default': None,
",
"  'name': 'BB_1258',
",
"  'nullable': True,
",
"  'primary_key': 0,
",
"  'type': INTEGER()},
",
" {'autoincrement': 'auto',
",
"  'default': None,
",
"  'name': 'BB_1259',
",
"  'nullable': True,
",
"  'primary_key': 0,
",
"  'type': INTEGER()},
",
" {'autoincrement': 'auto',
",
"  'default': None,
",
"  'name': 'BB_1260',
",
"  'nullable': True,
",
"  'primary_key': 0,
",
"  'type': INTEGER()},
",
" {'autoincrement': 'auto',
",
"  'default': None,
",
"  'name': 'BB_1264',
",
"  'nullable': True,
",
"  'primary_key': 0,
",
"  'type': INTEGER()},
",
" {'autoincrement': 'auto',
",
"  'default': None,
",
"  'name': 'BB_1265',
",
"  'nullable': True,
",
"  'primary_key': 0,
",
"  'type': INTEGER()},
",
" {'autoincrement': 'auto',
",
"  'default': None,
",
"  'name': 'BB_1273',
",
"  'nullable': True,
",
"  'primary_key': 0,
",
"  'type': INTEGER()},
",
" {'autoincrement': 'auto',
",
"  'default': None,
",
"  'name': 'BB_1275',
",
"  'nullable': True,
",
"  'primary_key': 0,
",
"  'type': INTEGER()},
",
" {'autoincrement': 'auto',
",
"  'default': None,
",
"  'name': 'BB_1276',
",
"  'nullable': True,
",
"  'primary_key': 0,
",
"  'type': INTEGER()},
",
" {'autoincrement': 'auto',
",
"  'default': None,
",
"  'name': 'BB_1277',
",
"  'nullable': True,
",
"  'primary_key': 0,
",
"  'type': INTEGER()},
",
" {'autoincrement': 'auto',
",
"  'default': None,
",
"  'name': 'BB_1278',
",
"  'nullable': True,
",
"  'primary_key': 0,
",
"  'type': INTEGER()},
",
" {'autoincrement': 'auto',
",
"  'default': None,
",
"  'name': 'BB_1279',
",
"  'nullable': True,
",
"  'primary_key': 0,
",
"  'type': INTEGER()},
",
" {'autoincrement': 'auto',
",
"  'default': None,
",
"  'name': 'BB_1280',
",
"  'nullable': True,
",
"  'primary_key': 0,
",
"  'type': INTEGER()},
",
" {'autoincrement': 'auto',
",
"  'default': None,
",
"  'name': 'BB_1281',
",
"  'nullable': True,
",
"  'primary_key': 0,
",
"  'type': INTEGER()},
",
" {'autoincrement': 'auto',
",
"  'default': None,
",
"  'name': 'BB_1282',
",
"  'nullable': True,
",
"  'primary_key': 0,
",
"  'type': INTEGER()},
",
" {'autoincrement': 'auto',
",
"  'default': None,
",
"  'name': 'BB_1283',
",
"  'nullable': True,
",
"  'primary_key': 0,
",
"  'type': INTEGER()},
",
" {'autoincrement': 'auto',
",
"  'default': None,
",
"  'name': 'BB_1284',
",
"  'nullable': True,
",
"  'primary_key': 0,
",
"  'type': INTEGER()},
",
" {'autoincrement': 'auto',
",
"  'default': None,
",
"  'name': 'BB_1285',
",
"  'nullable': True,
",
"  'primary_key': 0,
",
"  'type': INTEGER()},
",
" {'autoincrement': 'auto',
",
"  'default': None,
",
"  'name': 'BB_1286',
",
"  'nullable': True,
",
"  'primary_key': 0,
",
"  'type': INTEGER()},
",
" {'autoincrement': 'auto',
",
"  'default': None,
",
"  'name': 'BB_1287',
",
"  'nullable': True,
",
"  'primary_key': 0,
",
"  'type': INTEGER()},
",
" {'autoincrement': 'auto',
",
"  'default': None,
",
"  'name': 'BB_1288',
",
"  'nullable': True,
",
"  'primary_key': 0,
",
"  'type': INTEGER()},
",
" {'autoincrement': 'auto',
",
"  'default': None,
",
"  'name': 'BB_1289',
",
"  'nullable': True,
",
"  'primary_key': 0,
",
"  'type': INTEGER()},
",
" {'autoincrement': 'auto',
",
"  'default': None,
",
"  'name': 'BB_1290',
",
"  'nullable': True,
",
"  'primary_key': 0,
",
"  'type': INTEGER()},
",
" {'autoincrement': 'auto',
",
"  'default': None,
",
"  'name': 'BB_1291',
",
"  'nullable': True,
",
"  'primary_key': 0,
",
"  'type': INTEGER()},
",
" {'autoincrement': 'auto',
",
"  'default': None,
",
"  'name': 'BB_1292',
",
"  'nullable': True,
",
"  'primary_key': 0,
",
"  'type': INTEGER()},
",
" {'autoincrement': 'auto',
",
"  'default': None,
",
"  'name': 'BB_1293',
",
"  'nullable': True,
",
"  'primary_key': 0,
",
"  'type': INTEGER()},
",
" {'autoincrement': 'auto',
",
"  'default': None,
",
"  'name': 'BB_1294',
",
"  'nullable': True,
",
"  'primary_key': 0,
",
"  'type': INTEGER()},
",
" {'autoincrement': 'auto',
",
"  'default': None,
",
"  'name': 'BB_1295',
",
"  'nullable': True,
",
"  'primary_key': 0,
",
"  'type': INTEGER()},
",
" {'autoincrement': 'auto',
",
"  'default': None,
",
"  'name': 'BB_1296',
",
"  'nullable': True,
",
"  'primary_key': 0,
",
"  'type': INTEGER()},
",
" {'autoincrement': 'auto',
",
"  'default': None,
",
"  'name': 'BB_1297',
",
"  'nullable': True,
",
"  'primary_key': 0,
",
"  'type': INTEGER()},
",
" {'autoincrement': 'auto',
",
"  'default': None,
",
"  'name': 'BB_1298',
",
"  'nullable': True,
",
"  'primary_key': 0,
",
"  'type': INTEGER()},
",
" {'autoincrement': 'auto',
",
"  'default': None,
",
"  'name': 'BB_1308',
",
"  'nullable': True,
",
"  'primary_key': 0,
",
"  'type': INTEGER()},
",
" {'autoincrement': 'auto',
",
"  'default': None,
",
"  'name': 'BB_1309',
",
"  'nullable': True,
",
"  'primary_key': 0,
",
"  'type': INTEGER()},
",
" {'autoincrement': 'auto',
",
"  'default': None,
",
"  'name': 'BB_1310',
",
"  'nullable': True,
",
"  'primary_key': 0,
",
"  'type': INTEGER()},
",
" {'autoincrement': 'auto',
",
"  'default': None,
",
"  'name': 'BB_1374',
",
"  'nullable': True,
",
"  'primary_key': 0,
",
"  'type': INTEGER()},
",
" {'autoincrement': 'auto',
",
"  'default': None,
",
"  'name': 'BB_1415',
",
"  'nullable': True,
",
"  'primary_key': 0,
",
"  'type': INTEGER()},
",
" {'autoincrement': 'auto',
",
"  'default': None,
",
"  'name': 'BB_1439',
",
"  'nullable': True,
",
"  'primary_key': 0,
",
"  'type': INTEGER()},
",
" {'autoincrement': 'auto',
",
"  'default': None,
",
"  'name': 'BB_1441',
",
"  'nullable': True,
",
"  'primary_key': 0,
",
"  'type': INTEGER()},
",
" {'autoincrement': 'auto',
",
"  'default': None,
",
"  'name': 'BB_1443',
",
"  'nullable': True,
",
"  'primary_key': 0,
",
"  'type': INTEGER()},
",
" {'autoincrement': 'auto',
",
"  'default': None,
",
"  'name': 'BB_1486',
",
"  'nullable': True,
",
"  'primary_key': 0,
",
"  'type': INTEGER()},
",
" {'autoincrement': 'auto',
",
"  'default': None,
",
"  'name': 'BB_1487',
",
"  'nullable': True,
",
"  'primary_key': 0,
",
"  'type': INTEGER()},
",
" {'autoincrement': 'auto',
",
"  'default': None,
",
"  'name': 'BB_1489',
",
"  'nullable': True,
",
"  'primary_key': 0,
",
"  'type': INTEGER()},
",
" {'autoincrement': 'auto',
",
"  'default': None,
",
"  'name': 'BB_1490',
",
"  'nullable': True,
",
"  'primary_key': 0,
",
"  'type': INTEGER()},
",
" {'autoincrement': 'auto',
",
"  'default': None,
",
"  'name': 'BB_1491',
",
"  'nullable': True,
",
"  'primary_key': 0,
",
"  'type': INTEGER()},
",
" {'autoincrement': 'auto',
",
"  'default': None,
",
"  'name': 'BB_1494',
",
"  'nullable': True,
",
"  'primary_key': 0,
",
"  'type': INTEGER()},
",
" {'autoincrement': 'auto',
",
"  'default': None,
",
"  'name': 'BB_1495',
",
"  'nullable': True,
",
"  'primary_key': 0,
",
"  'type': INTEGER()},
",
" {'autoincrement': 'auto',
",
"  'default': None,
",
"  'name': 'BB_1497',
",
"  'nullable': True,
",
"  'primary_key': 0,
",
"  'type': INTEGER()},
",
" {'autoincrement': 'auto',
",
"  'default': None,
",
"  'name': 'BB_1499',
",
"  'nullable': True,
",
"  'primary_key': 0,
",
"  'type': INTEGER()},
",
" {'autoincrement': 'auto',
",
"  'default': None,
",
"  'name': 'BB_1500',
",
"  'nullable': True,
",
"  'primary_key': 0,
",
"  'type': INTEGER()},
",
" {'autoincrement': 'auto',
",
"  'default': None,
",
"  'name': 'BB_1501',
",
"  'nullable': True,
",
"  'primary_key': 0,
",
"  'type': INTEGER()},
",
" {'autoincrement': 'auto',
",
"  'default': None,
",
"  'name': 'BB_1502',
",
"  'nullable': True,
",
"  'primary_key': 0,
",
"  'type': INTEGER()},
",
" {'autoincrement': 'auto',
",
"  'default': None,
",
"  'name': 'BB_1503',
",
"  'nullable': True,
",
"  'primary_key': 0,
",
"  'type': INTEGER()},
",
" {'autoincrement': 'auto',
",
"  'default': None,
",
"  'name': 'BB_1504',
",
"  'nullable': True,
",
"  'primary_key': 0,
",
"  'type': INTEGER()},
",
" {'autoincrement': 'auto',
",
"  'default': None,
",
"  'name': 'BB_1505',
",
"  'nullable': True,
",
"  'primary_key': 0,
",
"  'type': INTEGER()},
",
" {'autoincrement': 'auto',
",
"  'default': None,
",
"  'name': 'BB_1506',
",
"  'nullable': True,
",
"  'primary_key': 0,
",
"  'type': INTEGER()},
",
" {'autoincrement': 'auto',
",
"  'default': None,
",
"  'name': 'BB_1507',
",
"  'nullable': True,
",
"  'primary_key': 0,
",
"  'type': INTEGER()},
",
" {'autoincrement': 'auto',
",
"  'default': None,
",
"  'name': 'BB_1508',
",
"  'nullable': True,
",
"  'primary_key': 0,
",
"  'type': INTEGER()},
",
" {'autoincrement': 'auto',
",
"  'default': None,
",
"  'name': 'BB_1510',
",
"  'nullable': True,
",
"  'primary_key': 0,
",
"  'type': INTEGER()},
",
" {'autoincrement': 'auto',
",
"  'default': None,
",
"  'name': 'BB_1511',
",
"  'nullable': True,
",
"  'primary_key': 0,
",
"  'type': INTEGER()},
",
" {'autoincrement': 'auto',
",
"  'default': None,
",
"  'name': 'BB_1512',
",
"  'nullable': True,
",
"  'primary_key': 0,
",
"  'type': INTEGER()},
",
" {'autoincrement': 'auto',
",
"  'default': None,
",
"  'name': 'BB_1513',
",
"  'nullable': True,
",
"  'primary_key': 0,
",
"  'type': INTEGER()},
",
" {'autoincrement': 'auto',
",
"  'default': None,
",
"  'name': 'BB_1514',
",
"  'nullable': True,
",
"  'primary_key': 0,
",
"  'type': INTEGER()},
",
" {'autoincrement': 'auto',
",
"  'default': None,
",
"  'name': 'BB_1515',
",
"  'nullable': True,
",
"  'primary_key': 0,
",
"  'type': INTEGER()},
",
" {'autoincrement': 'auto',
",
"  'default': None,
",
"  'name': 'BB_1516',
",
"  'nullable': True,
",
"  'primary_key': 0,
",
"  'type': INTEGER()},
",
" {'autoincrement': 'auto',
",
"  'default': None,
",
"  'name': 'BB_1517',
",
"  'nullable': True,
",
"  'primary_key': 0,
",
"  'type': INTEGER()},
",
" {'autoincrement': 'auto',
",
"  'default': None,
",
"  'name': 'BB_1518',
",
"  'nullable': True,
",
"  'primary_key': 0,
",
"  'type': INTEGER()},
",
" {'autoincrement': 'auto',
",
"  'default': None,
",
"  'name': 'BB_1519',
",
"  'nullable': True,
",
"  'primary_key': 0,
",
"  'type': INTEGER()},
",
" {'autoincrement': 'auto',
",
"  'default': None,
",
"  'name': 'BB_1521',
",
"  'nullable': True,
",
"  'primary_key': 0,
",
"  'type': INTEGER()},
",
" {'autoincrement': 'auto',
",
"  'default': None,
",
"  'name': 'BB_1524',
",
"  'nullable': True,
",
"  'primary_key': 0,
",
"  'type': INTEGER()},
",
" {'autoincrement': 'auto',
",
"  'default': None,
",
"  'name': 'BB_1526',
",
"  'nullable': True,
",
"  'primary_key': 0,
",
"  'type': INTEGER()},
",
" {'autoincrement': 'auto',
",
"  'default': None,
",
"  'name': 'BB_1527',
",
"  'nullable': True,
",
"  'primary_key': 0,
",
"  'type': INTEGER()},
",
" {'autoincrement': 'auto',
",
"  'default': None,
",
"  'name': 'BB_1530',
",
"  'nullable': True,
",
"  'primary_key': 0,
",
"  'type': INTEGER()},
",
" {'autoincrement': 'auto',
",
"  'default': None,
",
"  'name': 'BB_1531',
",
"  'nullable': True,
",
"  'primary_key': 0,
",
"  'type': INTEGER()},
",
" {'autoincrement': 'auto',
",
"  'default': None,
",
"  'name': 'BB_1532',
",
"  'nullable': True,
",
"  'primary_key': 0,
",
"  'type': INTEGER()},
",
" {'autoincrement': 'auto',
",
"  'default': None,
",
"  'name': 'BB_1533',
",
"  'nullable': True,
",
"  'primary_key': 0,
",
"  'type': INTEGER()},
",
" {'autoincrement': 'auto',
",
"  'default': None,
",
"  'name': 'BB_1534',
",
"  'nullable': True,
",
"  'primary_key': 0,
",
"  'type': INTEGER()},
",
" {'autoincrement': 'auto',
",
"  'default': None,
",
"  'name': 'BB_1535',
",
"  'nullable': True,
",
"  'primary_key': 0,
",
"  'type': INTEGER()},
",
" {'autoincrement': 'auto',
",
"  'default': None,
",
"  'name': 'BB_1536',
",
"  'nullable': True,
",
"  'primary_key': 0,
",
"  'type': INTEGER()},
",
" {'autoincrement': 'auto',
",
"  'default': None,
",
"  'name': 'BB_1537',
",
"  'nullable': True,
",
"  'primary_key': 0,
",
"  'type': INTEGER()},
",
" {'autoincrement': 'auto',
",
"  'default': None,
",
"  'name': 'BB_1539',
",
"  'nullable': True,
",
"  'primary_key': 0,
",
"  'type': INTEGER()},
",
" {'autoincrement': 'auto',
",
"  'default': None,
",
"  'name': 'BB_1540',
",
"  'nullable': True,
",
"  'primary_key': 0,
",
"  'type': INTEGER()},
",
" {'autoincrement': 'auto',
",
"  'default': None,
",
"  'name': 'BB_1541',
",
"  'nullable': True,
",
"  'primary_key': 0,
",
"  'type': INTEGER()},
",
" {'autoincrement': 'auto',
",
"  'default': None,
",
"  'name': 'BB_1542',
",
"  'nullable': True,
",
"  'primary_key': 0,
",
"  'type': INTEGER()},
",
" {'autoincrement': 'auto',
",
"  'default': None,
",
"  'name': 'BB_1543',
",
"  'nullable': True,
",
"  'primary_key': 0,
",
"  'type': INTEGER()},
",
" {'autoincrement': 'auto',
",
"  'default': None,
",
"  'name': 'BB_1544',
",
"  'nullable': True,
",
"  'primary_key': 0,
",
"  'type': INTEGER()},
",
" {'autoincrement': 'auto',
",
"  'default': None,
",
"  'name': 'BB_1545',
",
"  'nullable': True,
",
"  'primary_key': 0,
",
"  'type': INTEGER()},
",
" {'autoincrement': 'auto',
",
"  'default': None,
",
"  'name': 'BB_1546',
",
"  'nullable': True,
",
"  'primary_key': 0,
",
"  'type': INTEGER()},
",
" {'autoincrement': 'auto',
",
"  'default': None,
",
"  'name': 'BB_1547',
",
"  'nullable': True,
",
"  'primary_key': 0,
",
"  'type': INTEGER()},
",
" {'autoincrement': 'auto',
",
"  'default': None,
",
"  'name': 'BB_1548',
",
"  'nullable': True,
",
"  'primary_key': 0,
",
"  'type': INTEGER()},
",
" {'autoincrement': 'auto',
",
"  'default': None,
",
"  'name': 'BB_1549',
",
"  'nullable': True,
",
"  'primary_key': 0,
",
"  'type': INTEGER()},
",
" {'autoincrement': 'auto',
",
"  'default': None,
",
"  'name': 'BB_1550',
",
"  'nullable': True,
",
"  'primary_key': 0,
",
"  'type': INTEGER()},
",
" {'autoincrement': 'auto',
",
"  'default': None,
",
"  'name': 'BB_1551',
",
"  'nullable': True,
",
"  'primary_key': 0,
",
"  'type': INTEGER()},
",
" {'autoincrement': 'auto',
",
"  'default': None,
",
"  'name': 'BB_1552',
",
"  'nullable': True,
",
"  'primary_key': 0,
",
"  'type': INTEGER()},
",
" {'autoincrement': 'auto',
",
"  'default': None,
",
"  'name': 'BB_1553',
",
"  'nullable': True,
",
"  'primary_key': 0,
",
"  'type': INTEGER()},
",
" {'autoincrement': 'auto',
",
"  'default': None,
",
"  'name': 'BB_1554',
",
"  'nullable': True,
",
"  'primary_key': 0,
",
"  'type': INTEGER()},
",
" {'autoincrement': 'auto',
",
"  'default': None,
",
"  'name': 'BB_1555',
",
"  'nullable': True,
",
"  'primary_key': 0,
",
"  'type': INTEGER()},
",
" {'autoincrement': 'auto',
",
"  'default': None,
",
"  'name': 'BB_1556',
",
"  'nullable': True,
",
"  'primary_key': 0,
",
"  'type': INTEGER()},
",
" {'autoincrement': 'auto',
",
"  'default': None,
",
"  'name': 'BB_1557',
",
"  'nullable': True,
",
"  'primary_key': 0,
",
"  'type': INTEGER()},
",
" {'autoincrement': 'auto',
",
"  'default': None,
",
"  'name': 'BB_1558',
",
"  'nullable': True,
",
"  'primary_key': 0,
",
"  'type': INTEGER()},
",
" {'autoincrement': 'auto',
",
"  'default': None,
",
"  'name': 'BB_1561',
",
"  'nullable': True,
",
"  'primary_key': 0,
",
"  'type': INTEGER()},
",
" {'autoincrement': 'auto',
",
"  'default': None,
",
"  'name': 'BB_1562',
",
"  'nullable': True,
",
"  'primary_key': 0,
",
"  'type': INTEGER()},
",
" {'autoincrement': 'auto',
",
"  'default': None,
",
"  'name': 'BB_1563',
",
"  'nullable': True,
",
"  'primary_key': 0,
",
"  'type': INTEGER()},
",
" {'autoincrement': 'auto',
",
"  'default': None,
",
"  'name': 'BB_1564',
",
"  'nullable': True,
",
"  'primary_key': 0,
",
"  'type': INTEGER()},
",
" {'autoincrement': 'auto',
",
"  'default': None,
",
"  'name': 'BB_1572',
",
"  'nullable': True,
",
"  'primary_key': 0,
",
"  'type': INTEGER()},
",
" {'autoincrement': 'auto',
",
"  'default': None,
",
"  'name': 'BB_1573',
",
"  'nullable': True,
",
"  'primary_key': 0,
",
"  'type': INTEGER()},
",
" {'autoincrement': 'auto',
",
"  'default': None,
",
"  'name': 'BB_1574',
",
"  'nullable': True,
",
"  'primary_key': 0,
",
"  'type': INTEGER()},
",
" {'autoincrement': 'auto',
",
"  'default': None,
",
"  'name': 'BB_1576',
",
"  'nullable': True,
",
"  'primary_key': 0,
",
"  'type': INTEGER()},
",
" {'autoincrement': 'auto',
",
"  'default': None,
",
"  'name': 'BB_1577',
",
"  'nullable': True,
",
"  'primary_key': 0,
",
"  'type': INTEGER()},
",
" {'autoincrement': 'auto',
",
"  'default': None,
",
"  'name': 'BB_1581',
",
"  'nullable': True,
",
"  'primary_key': 0,
",
"  'type': INTEGER()},
",
" {'autoincrement': 'auto',
",
"  'default': None,
",
"  'name': 'BB_1601',
",
"  'nullable': True,
",
"  'primary_key': 0,
",
"  'type': INTEGER()}]"
]
},
"execution_count": 7,
"metadata": {},
"output_type": "execute_result"
}
],
"source": [
"inspector.get_columns('samples')"
]
},
{
"cell_type": "code",
"execution_count": 41,
"metadata": {},
"outputs": [
{
"data": {
"text/plain": [
"{'autoincrement': 'auto',
",
" 'default': None,
",
" 'name': 'SAMPLEID',
",
" 'nullable': False,
",
" 'primary_key': 1,
",
" 'type': INTEGER()}"
]
},
"execution_count": 41,
"metadata": {},
"output_type": "execute_result"
}
],
"source": [
"inspector.get_columns('samples_metadata')[0]"
]
},
{
"cell_type": "code",
"execution_count": 9,
"metadata": {},
"outputs": [
{
"data": {
"text/plain": [
"[(1, 'Archaea;Euryarchaeota;Halobacteria;Halobacteriales;Halobacteriaceae;Halococcus'),
",
" (2, 'Archaea;Euryarchaeota;Halobacteria;Halobacteriales;Halobacteriaceae;Halococcus'),
",
" (3, 'Archaea;Euryarchaeota;Halobacteria;Halobacteriales;Halobacteriaceae;Natronorubrum'),
",
" (4, 'Archaea;Euryarchaeota;Methanobacteria;Methanobacteriales;Methanobacteriaceae;Methanobrevibacter'),
",
" (5, 'Archaea;Euryarchaeota;Methanobacteria;Methanobacteriales;Methanobacteriaceae;Methanobrevibacter'),
",
" (6, 'Archaea;Euryarchaeota;Methanobacteria;Methanobacteriales;Methanobacteriaceae;Methanobrevibacter'),
",
" (7, 'Bacteria'),
",
" (8, 'Bacteria'),
",
" (9, 'Bacteria'),
",
" (10, 'Bacteria')]"
]
},
"execution_count": 9,
"metadata": {},
"output_type": "execute_result"
}
],
"source": [
"# Use `engine.execute` to select and display the first 10 rows from the table
",
"
",
"engine.execute('SELECT * FROM otu LIMIT 10').fetchall()"
]
},
{
"cell_type": "code",
"execution_count": 10,
"metadata": {},
"outputs": [
{
"data": {
"text/plain": [
"[(1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0),
",
" (2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0)]"
]
},
"execution_count": 10,
"metadata": {},
"output_type": "execute_result"
}
],
"source": [
"engine.execute('SELECT * FROM samples LIMIT 2').fetchall()"
]
},
{
"cell_type": "code",
"execution_count": 11,
"metadata": {},
"outputs": [
{
"data": {
"text/plain": [
"[(940, 'BellyButtonsScienceOnline', 'Caucasian', 'F', 24, 2, 'I', 'Beaufort/NC', 'usa', 22306, 'usa', 22306, 'no', 'no', 8852, 37.17222214, 54.5, 0.0, 1, 0.0, 33.99000168, 25.5),
",
" (941, '0', 'Caucasian/Midleastern', 'F', 34, 1, 'I', 'Chicago/IL', '0', 0, '0', 0, '0', '0', 0, 0.0, 0.0, 0.0, 0, 0.0, 0.0, 0.0),
",
" (943, 'BellyButtonsScienceOnline', 'Caucasian', 'F', 49, 1, 'I', 'Omaha/NE', '0', 0, '0', 0, '0', '0', 0, 0.0, 0.0, 0.0, 0, 0.0, 0.0, 0.0),
",
" (944, 'BellyButtonsScienceOnline', 'European', 'M', 44, 1, 'I', 'NewHaven/CT', 'usa', 7079, 'usa', 8822, 'no', 'yes', 0, 35.81666565, 16.0, 0.0, 0, 6567.0, 32.40333176, 28.5),
",
" (945, 'BellyButtonsScienceOnline', 'Caucasian', 'F', 48, 1, 'I', 'Philidelphia/PA', 'usa', 84404, 'usa', 96025, 'no', 'no', 0, 37.78333282, 4.0, 0.0, 0, 5613.0, 33.63444519, 24.0)]"
]
},
"execution_count": 11,
"metadata": {},
"output_type": "execute_result"
}
],
"source": [
"engine.execute('SELECT * FROM samples_metadata LIMIT 5').fetchall()"
]
},
{
"cell_type": "code",
"execution_count": 12,
"metadata": {
"collapsed": true
},
"outputs": [],
"source": [
"# Reflect Database into ORM class
",
"Samples = Base.classes.samples
",
"Metadata = Base.classes.samples_metadata
",
"Otu = Base.classes.otu"
]
},
{
"cell_type": "code",
"execution_count": 13,
"metadata": {
"collapsed": true
},
"outputs": [],
"source": [
"# Start a session to query the database
",
"session = Session(engine)"
]
},
{
"cell_type": "code",
"execution_count": 18,
"metadata": {},
"outputs": [
{
"data": {
"text/plain": [
"[('Caucasian',),
",
" ('Caucasian/Midleastern',),
",
" ('Caucasian',),
",
" ('European',),
",
" ('Caucasian',)]"
]
},
"execution_count": 18,
"metadata": {},
"output_type": "execute_result"
}
],
"source": [
"engine.execute('SELECT ETHNICITY FROM samples_metadata LIMIT 5').fetchall()"
]
},
{
"cell_type": "code",
"execution_count": 29,
"metadata": {},
"outputs": [],
"source": [
"test = engine.execute('SELECT ETHNICITY FROM samples_metadata').fetchall()"
]
},
{
"cell_type": "code",
"execution_count": 31,
"metadata": {},
"outputs": [
{
"data": {
"text/plain": [
"[('Caucasian',),
",
" ('Caucasian/Midleastern',),
",
" ('Caucasian',),
",
" ('European',),
",
" ('Caucasian',),
",
" ('Caucasian',),
",
" ('Caucasian',),
",
" ('Caucasian',),
",
" ('Caucasian',),
",
" ('Caucasian',),
",
" ('Caucasian',),
",
" ('Caucasian',),
",
" ('Caucasian',),
",
" ('Caucasian',),
",
" ('Caucasian',),
",
" ('Caucasian',),
",
" ('Caucasian',),
",
" ('Caucasian',),
",
" ('Caucasian',),
",
" ('Caucasian',),
",
" ('Caucasian',),
",
" ('Caucasian',),
",
" ('Caucasian',),
",
" ('Caucasian/Jewish',),
",
" ('Caucasian',),
",
" ('Caucasian/Asian',),
",
" ('Caucasian',),
",
" ('Asian(South)',),
",
" ('Caucasian',),
",
" ('Caucasian',),
",
" ('Caucasian',),
",
" ('Caucasian',),
",
" ('Hispanic',),
",
" ('Caucasian',),
",
" ('Caucasian',),
",
" ('Caucasian',),
",
" ('Caucasian',),
",
" ('Caucasian',),
",
" ('Caucasian',),
",
" ('Caucasian',),
",
" ('Caucasian',),
",
" ('Caucasian',),
",
" ('Caucasian',),
",
" ('Caucasian',),
",
" ('Caucasian',),
",
" ('Caucasian',),
",
" ('Caucasian',),
",
" ('Caucasian',),
",
" ('Caucasian',),
",
" ('Caucasian',),
",
" ('Caucasian',),
",
" ('Caucasian',),
",
" ('Caucasian',),
",
" ('0',),
",
" ('Black',),
",
" ('PacificIslander',),
",
" ('Caucasian',),
",
" ('Caucasian',),
",
" ('Caucasian',),
",
" ('Caucasian',),
",
" ('Caucasian',),
",
" ('Caucasian',),
",
" ('Caucasian',),
",
" ('Caucasian',),
",
" ('Black',),
",
" ('Caucasian',),
",
" ('Caucasian',),
",
" ('Caucasian',),
",
" ('Caucasian',),
",
" ('Caucasian',),
",
" ('Caucasian',),
",
" ('Black',),
",
" ('Caucasion',),
",
" ('White',),
",
" ('Black',),
",
" ('Black',),
",
" ('Black',),
",
" ('Caucasian',),
",
" ('0',),
",
" ('Caucasian',),
",
" ('Caucasian',),
",
" ('Caucasian',),
",
" ('Caucasian',),
",
" ('Caucasian',),
",
" ('Caucasian',),
",
" ('Caucasian',),
",
" ('Caucasian',),
",
" ('Caucasian',),
",
" ('Caucasian',),
",
" ('Caucasian',),
",
" ('Caucasian',),
",
" ('Caucasian',),
",
" ('0',),
",
" ('Caucasian',),
",
" ('Caucasian',),
",
" ('Caucasian',),
",
" ('Caucasian',),
",
" ('Caucasian',),
",
" ('Caucasian',),
",
" ('Caucasian',),
",
" ('Black',),
",
" ('Caucasian',),
",
" ('Caucasian',),
",
" ('Caucasian',),
",
" ('Caucasian',),
",
" ('Caucasian',),
",
" ('Caucasian',),
",
" ('Caucasian',),
",
" ('Caucasian',),
",
" ('Caucasian',),
",
" ('Caucasian',),
",
" ('Caucasian',),
",
" ('Caucasian',),
",
" ('Caucasian',),
",
" ('Caucasian',),
",
" ('Caucasian',),
",
" ('Caucasian',),
",
" ('Black',),
",
" ('Caucasian',),
",
" ('Caucasian',),
",
" ('Caucasian',),
",
" ('Caucasian',),
",
" ('Caucasian',),
",
" ('Caucasian',),
",
" ('Caucasian',),
",
" ('Caucasian',),
",
" ('Caucasian',),
",
" ('Caucasian',),
",
" ('Caucasian',),
",
" ('Caucasian',),
",
" ('0',),
",
" ('Caucasian',),
",
" ('Caucasian',),
",
" ('Caucasian',),
",
" ('Caucasian',),
",
" ('Caucasian',),
",
" ('Caucasian',),
",
" ('Caucasian',),
",
" ('Caucasian',),
",
" ('Hispanic',),
",
" ('Caucasian',),
",
" ('Caucasian',),
",
" ('Caucasian',),
",
" ('Caucasian',),
",
" ('Caucasian',),
",
" ('Caucasian',),
",
" ('Caucasian',),
",
" ('Caucasian',),
",
" ('Caucasian',),
",
" ('Caucasian',),
",
" ('Caucasian',),
",
" ('Asian(American)',),
",
" ('Caucasian',)]"
]
},
"execution_count": 31,
"metadata": {},
"output_type": "execute_result"
}
],
"source": [
"test"
]
},
{
"cell_type": "code",
"execution_count": null,
"metadata": {},
"outputs": [],
"source": []
},
{
"cell_type": "code",
"execution_count": null,
"metadata": {},
"outputs": [],
"source": []
},
{
"cell_type": "code",
"execution_count": null,
"metadata": {},
"outputs": [],
"source": []
},
{
"cell_type": "code",
"execution_count": null,
"metadata": {},
"outputs": [],
"source": []
},
{
"cell_type": "code",
"execution_count": null,
"metadata": {
"collapsed": true
},
"outputs": [],
"source": []
}
],
"metadata": {
"kernelspec": {
"display_name": "Python 3",
"language": "python",
"name": "python3"
},
"language_info": {
"codemirror_mode": {
"name": "ipython",
"version": 3
},
"file_extension": ".py",
"mimetype": "text/x-python",
"name": "python",
"nbconvert_exporter": "python",
"pygments_lexer": "ipython3",
"version": "3.6.2"
}
},
"nbformat": 4,
"nbformat_minor": 2
}